[colors]
[colors.primary]
background = "#ffffff"   # base00
foreground = "#3b83bd"   # base05

[colors.cursor]
text = "#ffffff"
cursor = "#45475a"       # base04/base09

[colors.selection]
text = "#0a64f5"         # base06
background = "#afdafc"   # base02

[colors.normal]
black   = "#45475a"      # base03 (comments)
red     = "#e71852"      # base08
green   = "#45c43b"      # base0B
yellow  = "#eda912"      # base0A
blue    = "#0a64f5"      # base0D
magenta = "#0a64f5"      # base0E
cyan    = "#008aff"      # base0C
white   = "#080809"      # base06

[colors.bright]
black   = "#45475a"
red     = "#ff000a"
green   = "#318c2a"
yellow  = "#edc612"
blue    = "#0a64f5"
magenta = "#0047ab"
cyan    = "#008aff"
white   = "#121212"