[colors]
[colors.primary]
background = "#ffffff"
foreground = "#1e293b"

[colors.cursor]
text = "#ffffff"
cursor = "#0a64f5"

[colors.selection]
text = "#0f172a"
background = "#cbd5e1"

[colors.normal]
black   = "#f1f5f9"
red     = "#e11d48"
green   = "#059669"
yellow  = "#d97706"
blue    = "#0a64f5"
magenta = "#7c3aed"
cyan    = "#0284c7"
white   = "#1e293b"

[colors.bright]
black   = "#94a3b8"
red     = "#f43f5e"
green   = "#10b981"
yellow  = "#f59e0b"
blue    = "#2563eb"
magenta = "#8b5cf6"
cyan    = "#06b6d4"
white   = "#0f172a"
