# Accent and UI colors
accent = "#0a64f5"                 # base04/base09
active_border_color = "#3b83bd"    # base0D
active_tab_background = "#77dde7"  # base02

# Cursor colors
cursor = "#151719"                 # base0C

# Primary colors
foreground = "#3b83bd"             # base05
background = "#ffffff"             # base00

# Selection colors
selection_foreground = "#030303"   # base06
selection_background = "#77dde7"   # base02

# Normal colors (ANSI 0-7)
color0 = "#afdafc"   # base03
color1 = "#1560bd"   # base08
color2 = "#0a64f5"   # base0B
color3 = "#6495ed"   # base0A
color4 = "#3b83bd"   # base0D
color5 = "#0047ab"   # base0E
color6 = "#151719"   # base0C
color7 = "#030303"   # base06

# Bright colors (ANSI 8-15)
color8  = "#afdafc"  # base03
color9  = "#1560bd"  # base08
color10 = "#0a64f5"  # base0B
color11 = "#6495ed"  # base0A
color12 = "#0a64f5"  # base09
color13 = "#0047ab"  # base0E
color14 = "#151719"  # base0C
color15 = "#f8f8ff"  # base07