# Background and foreground colors
background = #ffffff        # base00
foreground = #3b83bd        # base05

# Cursor
cursor-color = #151719      # base0C
selection-background = #77dde7  # base02
selection-foreground = #030303  # base06

# Standard colors
palette = 0=#afdafc   # base03
palette = 1=#1560bd   # base08
palette = 2=#0a64f5   # base0B
palette = 3=#6495ed   # base0A
palette = 4=#3b83bd   # base0D
palette = 5=#0047ab   # base0E
palette = 6=#151719   # base0C
palette = 7=#030303   # base06

# Bright colors
palette = 8=#afdafc   # base03
palette = 9=#1560bd   # base08
palette = 10=#0a64f5  # base0B
palette = 11=#6495ed  # base0A
palette = 12=#0a64f5  # base09
palette = 13=#0047ab  # base0E
palette = 14=#151719  # base0C
palette = 15=#f8f8ff  # base07