background = #ffffff
foreground = #3b83bd

cursor-color = #151719
cursor-text = #ffffff

selection-background = #77dde7
selection-foreground = #030303

# 16-color palette
palette = 0=#afdafc
palette = 1=#1560bd
palette = 2=#0a64f5
palette = 3=#6495ed
palette = 4=#3b83bd
palette = 5=#0047ab
palette = 6=#151719
palette = 7=#030303

palette = 8=#afdafc
palette = 9=#1560bd
palette = 10=#0a64f5
palette = 11=#6495ed
palette = 12=#0a64f5
palette = 13=#0047ab
palette = 14=#151719
palette = 15=#f8f8ff
