# Background and foreground colors
background = #ffffff
foreground = #121212

# Standard colors
palette = 0=#ffffff
palette = 1=#e71852
palette = 2=#45c43b
palette = 3=#eda912
palette = 4=#0a64f5
palette = 5=#0a64f5
palette = 6=#008aff
palette = 7=#889de5

# Bright colors
palette = 8=#45475a
palette = 9=#ff000a
palette = 10=#318c2a
palette = 11=#edc612
palette = 12=#5796cc
palette = 13=#5090f8
palette = 14=#008aff
palette = 15=#121212