$color = rgba(255, 255, 255, 1)          # base00
$inner_color = rgba(175, 218, 252, 0.66) # base03
$outer_color = rgba(59, 131, 189, 1)     # base0D

$font_color = rgba(21, 23, 25, 1)        # base0C
$placeholder_color = rgba(21, 23, 25, 0.7)

$check_color = rgba(10, 100, 245, 1)     # base04/base09