# Omarchy 4.0 White Air Theme - Hyprland Config
# Included in main hyprland.conf when active

$activeBorderColor = rgb(0a64f5) rgb(3b83bd) 45deg
$inactiveBorderColor = rgba(5983bd33)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
