# Base
background #ffffff
foreground #0a64f5

# Cursor
cursor #45475a
cursor_text_color #ffffff

# Selection
selection_background #afdafc
selection_foreground #0a64f5

# ANSI colors
color0  #45475a
color1  #e71852
color2  #45c43b
color3  #eda912
color4  #0a64f5
color5  #0a64f5
color6  #008aff
color7  #080809

# Bright colors
color8  #45475a
color9  #ff000a
color10 #318c2a
color11 #edc612
color12 #0a64f5
color13 #0047ab
color14 #008aff
color15 #121212