background            #ffffff   # base00
foreground            #3b83bd   # base05

selection_background  #77dde7   # base02
selection_foreground  #030303   # base06

cursor                #151719   # base0C

color0  #afdafc   # base03
color1  #1560bd   # base08
color2  #0a64f5   # base0B
color3  #6495ed   # base0A
color4  #3b83bd   # base0D
color5  #0047ab   # base0E
color6  #151719   # base0C
color7  #030303   # base06

color8  #afdafc   # base03
color9  #1560bd   # base08
color10 #0a64f5   # base0B
color11 #6495ed   # base0A
color12 #0a64f5   # base09
color13 #0047ab   # base0E
color14 #151719   # base0C
color15 #f8f8ff   # base07